# the default value for concurrency in each container will be 1


version: "3"
services:
  selenium-hub:
    image: seleniarm/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444" # for external connections
      - "4443:4443" # for internal connections and maybe for external connections like external nodes
      - "4442:4442" # for internal connections and maybe for external connections like external nodes

  chrome:
    image: seleniarm/node-chromium:117.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

#  firefox:
#    image: seleniarm/node-firefox:117.0
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#      - SE_NODE_MAX_SESSIONS=4